services:
  - type: web
    name: tareaflow
    env: php
    plan: free
    branch: main
    repo: https://github.com/tu-usuario/tu-repositorio
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_NAME
        value: TareaFlow
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        generateValue: true  # Render generará la URL automáticamente
      - key: APP_KEY
        sync: false  # Copiarás este valor manualmente desde tu .env local
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: 3306
    numInstances: 1

databases:
  - name: tareaflow_db
    databaseName: tareaflow_db
    user: tareaflow_user